### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by snaptopixel** [stencil-community/welcome#3]
Thank you @rwaskiewicz @a-giuliano for starting this org! How do we join as contributors and what will the process be for when/how projects are added?

**Comment by rwaskiewicz** [comment]
👋 👋 

@a-giuliano and I are sitting down later this afternoon to hammer out details like this. More to come! 🙂

**Comment by rwaskiewicz** [comment]
@snaptopixel 👋 

@a-giuliano and I talked this afternoon and came up with the following:

For adding projects:
1. There will be some projects that get added by the Stencil core team (e.g. the Stencil App Starter)
2. We will be implementing a proposal system, similar to what the Capacitor Community does today - there, folks can suggest a new package 

For folks looking to join as contributors, we see two possible routes of participating:
1. As a project lead, where someone (or a few people) are responsible for the direction/stewardship of the project. As we move existing projects + add brand new ones to this community org, Anthony and I will help facilitate getting folks stood up. We plan on them to raise their hand and express interest in a particular project, and can help move things along from there. As individual projects mature, our hope is that we become less of a necessity in the day to day operation (but will still be around to help!)
3. As a contributor, we expect contributing to these projects to be similar to any other open source project - folks can open issues, implement/raise pull requests for maintainers/leads to review, etc.

I know that's all a little high level - @a-giuliano is going to be codifying these things with more detail over the next few days (we'll link the associated PRs when they come up!)

**Comment by snaptopixel** [comment]
Perfect, thanks for the detailed response @rwaskiewicz! Looking forward to more collaborating.
